lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.nt

Remove type "book" when type is archivedWebPage

---

lodmill-rd/doc/scripts/hbz01/stats/stats.sh

See hbz/nwbib#102.
See hbz/nwbib#106.

Add script which generates beacons about subjects in the NWBib dataset

---

lodmill-rd/doc/scripts/hbz01/stats/stats.sh

See hbz/nwbib#106.
See hbz/nwbib#102.

Adjust the link template and fixed a regex to get only gnd subjects

---

lodmill-rd/doc/scripts/hbz01/stats/stats.sh

See https://github.com/hbz/nwbib/issues/102#issuecomment-103039221 and https://github.com/hbz/nwbib/issues/106#issuecomment-103040650.

Re-adjust URL templates for NWBib BEACON files.

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.nt

Replace dc:subject & dc:contributor by lv properties.

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml

Remove rdamediatype:1005.

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.nt

See #271. Testfile has yet to be adjusted. Hope it works this time. :wink:

Add class lv:EditedVolume when 900sf="Aufsatzsammlung".

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml

Remove field 700n as indictor for being a NWBiB resource

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.nt

See hbz/nwbib#104.
* adjust test data

Remove double angle brackets from data

---

lodmill-rd/src/main/java/org/lobid/lodmill/ElasticsearchIndexer.java

Add rule to switch index alias only when same index prefix name

---

lodmill-rd/src/main/java/org/lobid/lodmill/RdfModel2ElasticsearchJsonLd.java
lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Issue 497 volumes as bnodes

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

See #497.
- adjust morph
- adjust test sets

Revert to use also bibo:volume

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Issue 702 add lv contained in

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

See hbz/lobid#158.
* adjust tests

Remove dct:contributor when dct:creator

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Remove prefixes "Kreis" and "Regierungsbezirk" transforming 700n

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Remove past publishers and places (field 418) from morph.

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Remove fields 611-616 (Hinw. z. Sekundärform") from morph.

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Issue use colon instead of comma generating volume

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Add mapping from [Red.] to marcrel:red.

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Issue hbz lobid 249 field200b koerperschaften

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Don't remove this data from persons as subjects, though.
See hbz/lobid#244.
- adjust tests

Remove date of birth/death from creators and contributor

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

See #741.
Also added rdvocab:statementOfResponsibility coming from superordinated
resources.
- updated tests

Add missing creators coming from superordinated resources

---

lodmill-rd/src/main/resources/index-config.json

Issue hbz lobid 262 doi not searchable

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

There are many ways to build the title.
See #761.
- adjust tests

Fix order of precedence of title

---

lodmill-rd/src/main/java/org/lobid/lodmill/ElasticsearchIndexer.java
lodmill-rd/src/main/java/org/lobid/lodmill/PipeEncodeTriples.java
lodmill-rd/src/main/java/org/lobid/lodmill/RdfModel2ElasticsearchEtikettJsonLd.java
lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/java/org/lobid/lodmill/MabXml2ElasticsearchLobidTest.java
lodmill-rd/src/test/java/org/lobid/lodmill/MabXml2lobidSingleFilesTest.java
lodmill-rd/src/test/resources/hbz01.es.nt

- use code from https://github.com/hbz/lobid-rdf-to-json
- use labels from etikett
- build nested json structure
- add context into documents
- update tests

Switch json transformation to new JsonConverter

---

lodmill-ld/src/main/resources/index-config.json
lodmill-rd/src/main/resources/index-config.json

Handle umlauts and their resolution as equivalent
See http://github.com/hbz/nwbib/issues/issue/208
For details see:
http://snowball.tartarus.org/algorithms/german2/stemmer.html
For API tests see: https://github.com/hbz/lobid/pull/280
@dr0i: Could you deploy this to the staging index?

Set up german_analyzer with snowball German2 token filter

---

lodmill-ld/src/main/resources/index-config.json
lodmill-rd/src/main/resources/index-config.json

Add missing fields and set default analyzer for `_all` field.
See issue and API tests:
https://github.com/hbz/nwbib/issues/208
https://github.com/hbz/lobid/pull/281

Update tests and index config for german analyzer

---

lodmill-rd/src/main/resources/index-config.json

See https://github.com/hbz/lobid/issues/72

Issue 72 urn case insensitive

---

lodmill-ld/src/main/resources/index-config.json
lodmill-rd/src/main/resources/index-config.json

See https://github.com/hbz/nwbib/issues/213

Keep not_analyzed raw field for facetting over subjectChain

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/CT003012479.nt
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

See hbz/lobid-resources#29.
- udpate tests

Improve name of subject chain elements

---

lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml
lodmill-rd/src/test/resources/hbz01.es.nt
lodmill-rd/src/test/resources/hbz01.nt

Fixes https://github.com/hbz/lobid-resources/issues/33
Fixes https://github.com/hbz/lobid/issues/298
@fsteeg I didn't manage to run `mvn clean install` in lodmill and check the changes. As everything worked finde in lobid-resources, this should be no problem, though, and can probably be deployed as is.

Adjust transformation for edoweb requirements
